version: '3.9'

services:

  cassandranode1:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandranode1
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - cassandra_node1_data:/bitnami
    networks:
      cassandranet:
        ipv4_address: 172.24.0.2
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandranode1
      - CASSANDRA_BROADCAST_ADDRESS=cassandranode1
      - CASSANDRA_SEEDS=cassandranode1,cassandranode2,cassandranode3
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M


  cassandranode2:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandranode2
    ports:
      - "7001:7001"
      - "9043:9043"
    volumes:
      - cassandra_node2_data:/bitnami
    networks:
      cassandranet:
        ipv4_address: 172.24.0.3
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandranode2
      - CASSANDRA_BROADCAST_ADDRESS=cassandranode2
      - CASSANDRA_SEEDS=cassandranode1,cassandranode2,cassandranode3
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandranode3:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandranode3
    ports:
      - "7002:7002"
      - "9044:9044"
    volumes:
      - cassandra_node3_data:/bitnami
    networks:
      cassandranet:
        ipv4_address: 172.24.0.4
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandranode3
      - CASSANDRA_BROADCAST_ADDRESS=cassandranode3
      - CASSANDRA_SEEDS=cassandranode1,cassandranode2,cassandranode3
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

volumes:
  cassandra_node1_data:
    driver: local
  cassandra_node2_data:
    driver: local
  cassandra_node3_data:
    driver: local

networks:
  cassandranet:
    ipam:
      driver: default
      config:
      - subnet: 172.24.0.0/24
        ip_range: 172.24.0.0/24
        gateway: 172.24.0.1